language: rust

sudo: false

notifications:
    email: false

branches:
    only: master

script:
    - cargo build --verbose
    - cargo test  --verbose
    - cargo build --verbose --all-features
    - cargo test  --verbose --all-features
